window.env = {
  "TERM_PROGRAM": "vscode",
  "NODE": "/usr/local/bin/node",
  "INIT_CWD": "/Users/kabash/Documents/shop-frontend",
  "TERM": "xterm-256color",
  "SHELL": "/bin/zsh",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "TMPDIR": "/var/folders/pd/t3bklxd57fddpy9s80nr59ww0000gn/T/",
  "TERM_PROGRAM_VERSION": "1.54.1",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "COLOR": "1",
  "USER": "kabash",
  "COMMAND_MODE": "unix2003",
  "npm_config_globalconfig": "/usr/local/etc/npmrc",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.zPEa67lVDG/Listeners",
  "__CF_USER_TEXT_ENCODING": "0x1F5:0:2",
  "npm_execpath": "/usr/local/lib/node_modules/npm/bin/npm-cli.js",
  "npm_config_init.module": "/Users/kabash/.npm-init.js",
  "PATH": "/Users/kabash/Documents/shop-frontend/node_modules/.bin:/Users/kabash/Documents/node_modules/.bin:/Users/kabash/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
  "npm_package_json": "/Users/kabash/Documents/shop-frontend/package.json",
  "_": "/Users/kabash/Documents/shop-frontend/node_modules/.bin/react-dotenv",
  "npm_config_userconfig": "/Users/kabash/.npmrc",
  "npm_config_init_module": "/Users/kabash/.npm-init.js",
  "__CFBundleIdentifier": "com.microsoft.VSCode",
  "npm_command": "start",
  "PWD": "/Users/kabash/Documents/shop-frontend",
  "npm_lifecycle_event": "start",
  "EDITOR": "vi",
  "npm_package_name": "shop-frontend",
  "LANG": "en_GB.UTF-8",
  "XPC_FLAGS": "0x0",
  "npm_config_node_gyp": "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "npm_package_version": "0.1.0",
  "XPC_SERVICE_NAME": "0",
  "SHLVL": "2",
  "HOME": "/Users/kabash",
  "VSCODE_GIT_ASKPASS_MAIN": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
  "npm_config_cache": "/Users/kabash/.npm",
  "LOGNAME": "kabash",
  "npm_lifecycle_script": "react-dotenv && react-scripts start",
  "VSCODE_GIT_IPC_HANDLE": "/var/folders/pd/t3bklxd57fddpy9s80nr59ww0000gn/T/vscode-git-d6a36b26b3.sock",
  "npm_config_user_agent": "npm/7.5.6 node/v14.15.0 darwin x64",
  "VSCODE_GIT_ASKPASS_NODE": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)",
  "GIT_ASKPASS": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
  "npm_node_execpath": "/usr/local/bin/node",
  "npm_config_prefix": "/usr/local",
  "COLORTERM": "truecolor",
  "SHOP_REST_API_BASE_URL": "http://localhost:5000/api",
  "EXPOSED_API_URL": "https://appleshop.loca.lt/api",
  "IMAGES_URL": "http://localhost:5000"
};